package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/multica-ai/multica/server/internal/cli"
)

var logsCmd = &cobra.Command{
	Use:   "logs",
	Short: "Export agent run logs",
}

var logsExportCmd = &cobra.Command{
	Use:   "export <task-id>",
	Short: "Export a redacted log bundle for a task run",
	Long: `Export a task run's structured transcript, run metadata, and an AI-ready
summary as one JSON bundle.

The bundle is generated by the server — the same generator behind the web and
desktop export dialogs — so the file this command writes is exactly the artifact
those surfaces preview and upload. Token-, password-, and environment-value
shaped material is masked before it ever leaves the server.

Ranges:
  run     this run only (default)
  hours   every run of the same issue whose entries fall in the last N hours
  task    the issue's whole run history

To report the bundle on the issue instead of keeping it local, pass --report.
The bundle is pushed into the workspace's log repository when one is
configured, and the comment keeps a link to the committed file along with the
human owner's mention; with no repository — or a push that fails — the file is
uploaded through the ordinary issue-comment attachment path instead, so the
report is never lost. An agent- or squad-assigned issue mentions its human
creator rather than the assignee, so reporting can never queue another agent
run; name one explicitly with --mention to override that.`,
	Example: `  # Export the run's log bundle into the current directory
  $ multica logs export 01a0b577-06b6-786e-8df6-3ebf70edf6d2

  # The last 6 hours of the issue's runs, written to ./exports
  $ multica logs export 01a0b577-06b6-786e-8df6-3ebf70edf6d2 --scope hours --hours 6 -o ./exports

  # Write the bundle to stdout (metadata goes to stderr), then report it
  $ multica logs export 01a0b577-06b6-786e-8df6-3ebf70edf6d2 --stdout > bundle.json

  # Export and report it on the issue in one action
  $ multica logs export 01a0b577-06b6-786e-8df6-3ebf70edf6d2 --report`,
	Args: exactArgs(1),
	RunE: runLogsExport,
}

func init() {
	logsCmd.AddCommand(logsExportCmd)
	logsExportCmd.Flags().String("scope", "run", "Export range: run, hours, or task")
	logsExportCmd.Flags().Int("hours", 0, "Lookback window in hours; required with --scope hours")
	logsExportCmd.Flags().StringP("output-dir", "o", ".", "Directory to write the bundle into")
	logsExportCmd.Flags().String("output-file", "", "Exact path to write the bundle to (overrides --output-dir)")
	logsExportCmd.Flags().Bool("stdout", false, "Write the bundle JSON to stdout instead of a file")
	logsExportCmd.Flags().Bool("report", false, "Also report the bundle on the task's issue: push it to the workspace log repo, or attach it as a comment, and mention its human owner")
	logsExportCmd.Flags().String("mention", "", "Override the --report mention as <type>:<id> (member, agent, or squad; an agent/squad mention queues a run)")
}

// exportedBundle is the subset of the artifact this command reads back. The
// artifact itself is opaque bytes here: re-encoding it would break the promise
// that the CLI writes exactly what the server produced.
type exportedBundle struct {
	Task struct {
		ID              string `json:"id"`
		IssueID         string `json:"issue_id"`
		IssueIdentifier string `json:"issue_identifier"`
		Scope           struct {
			Kind  string `json:"kind"`
			Hours int    `json:"hours"`
		} `json:"scope"`
	} `json:"task"`
	RunCount   int  `json:"run_count"`
	EntryCount int  `json:"entry_count"`
	Truncated  bool `json:"truncated"`
	// Redaction is the artifact's own statement about its masking. A bundle
	// built from a run whose environment could not be read is only
	// pattern-redacted, and the CLI surfaces that rather than letting the
	// summary's "已自动脱敏" line stand unqualified. It is a pointer so an
	// artifact from a server that predates the marker reads as "unknown"
	// instead of falsely reading as "incomplete".
	Redaction *struct {
		Complete bool   `json:"complete"`
		Note     string `json:"note,omitempty"`
	} `json:"redaction"`
	SummaryMarkdown string `json:"summary_markdown"`
}

func runLogsExport(cmd *cobra.Command, args []string) error {
	scope, _ := cmd.Flags().GetString("scope")
	hours, _ := cmd.Flags().GetInt("hours")
	if err := validateLogsExportScope(scope, hours); err != nil {
		return err
	}

	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}

	// A report uploads the bundle, so give the request the same longer budget
	// the comment-attachment path uses.
	timeout := cli.APITimeout()
	if report, _ := cmd.Flags().GetBool("report"); report {
		timeout = cli.AtLeastAPITimeout(60 * time.Second)
	}
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	path := "/api/tasks/" + args[0] + "/logs/export?scope=" + scope
	if scope == "hours" {
		path += "&hours=" + strconv.Itoa(hours)
	}
	body, headers, err := client.GetBytes(ctx, path)
	if err != nil {
		return fmt.Errorf("export logs: %w", err)
	}

	var bundle exportedBundle
	if err := json.Unmarshal(body, &bundle); err != nil {
		return fmt.Errorf("decode log bundle: %w", err)
	}

	filename := filenameFromHeaders(headers)
	if filename == "" {
		filename = "log-export.json"
	}

	result := map[string]any{
		"task_id":          bundle.Task.ID,
		"issue_id":         bundle.Task.IssueID,
		"issue_identifier": bundle.Task.IssueIdentifier,
		"scope":            bundle.Task.Scope.Kind,
		"run_count":        bundle.RunCount,
		"entry_count":      bundle.EntryCount,
		"truncated":        bundle.Truncated,
		"summary_markdown": bundle.SummaryMarkdown,
	}
	if bundle.Redaction != nil && !bundle.Redaction.Complete {
		result["redaction_complete"] = false
		result["redaction_note"] = bundle.Redaction.Note
	}

	// stdout is the artifact's channel. `multica logs export <id> --stdout >
	// bundle.json` must produce a file that parses as exactly one JSON
	// document, so in that mode the metadata JSON moves to stderr rather than
	// being appended to the bundle on stdout.
	metaOut := io.Writer(os.Stdout)
	toStdout, _ := cmd.Flags().GetBool("stdout")
	if toStdout {
		if _, err := os.Stdout.Write(body); err != nil {
			return fmt.Errorf("write bundle to stdout: %w", err)
		}
		metaOut = os.Stderr
	} else {
		dest, err := writeLogBundle(cmd, filename, body)
		if err != nil {
			return err
		}
		result["path"] = dest
		result["filename"] = filename
		result["size_bytes"] = len(body)
		fmt.Fprintln(os.Stderr, "Exported:", dest)
	}

	if report, _ := cmd.Flags().GetBool("report"); report {
		reported, err := reportLogBundle(ctx, cmd, client, args[0], bundle, filename, body)
		if err != nil {
			return err
		}
		result["report"] = reported
	}

	return cli.PrintJSON(metaOut, result)
}

func validateLogsExportScope(scope string, hours int) error {
	switch scope {
	case "run", "task":
		if hours != 0 {
			return fmt.Errorf("--hours only applies to --scope hours")
		}
	case "hours":
		if hours <= 0 {
			return fmt.Errorf("--scope hours requires --hours N (1-%d)", 24*30)
		}
	default:
		return fmt.Errorf("invalid --scope %q: want run, hours, or task", scope)
	}
	return nil
}

// writeLogBundle writes the artifact and returns its absolute path. The output
// directory is created so `-o ./exports` works in a clean workdir.
func writeLogBundle(cmd *cobra.Command, filename string, body []byte) (string, error) {
	if explicit, _ := cmd.Flags().GetString("output-file"); explicit != "" {
		if dir := filepath.Dir(explicit); dir != "" && dir != "." {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return "", fmt.Errorf("create output directory: %w", err)
			}
		}
		if err := os.WriteFile(explicit, body, 0o644); err != nil {
			return "", fmt.Errorf("write bundle: %w", err)
		}
		abs, err := filepath.Abs(explicit)
		if err != nil {
			return explicit, nil
		}
		return abs, nil
	}

	outputDir, _ := cmd.Flags().GetString("output-dir")
	if outputDir == "" {
		outputDir = "."
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return "", fmt.Errorf("create output directory: %w", err)
	}
	dest := filepath.Join(outputDir, filename)
	if err := os.WriteFile(dest, body, 0o644); err != nil {
		return "", fmt.Errorf("write bundle: %w", err)
	}
	abs, err := filepath.Abs(dest)
	if err != nil {
		return dest, nil
	}
	return abs, nil
}

// logExportPush mirrors the push response the web dialog consumes. The
// pointer on RedactionComplete matters: a server that predates the marker
// sends null, which must read as "not proven clean" rather than as clean.
type logExportPush struct {
	Pushed            bool   `json:"pushed"`
	Filename          string `json:"filename"`
	Path              string `json:"path"`
	URL               string `json:"url"`
	Branch            string `json:"branch"`
	Repo              string `json:"repo"`
	SummaryMarkdown   string `json:"summary_markdown"`
	EntryCount        int    `json:"entry_count"`
	RunCount          int    `json:"run_count"`
	SizeBytes         int    `json:"size_bytes"`
	RedactionComplete *bool  `json:"redaction_complete"`
	RedactionNote     string `json:"redaction_note,omitempty"`
	Truncated         bool   `json:"truncated"`
}

// reportLogBundle reports the artifact on its issue, preferring the workspace
// log repository over a comment attachment.
//
// The order is the whole point of the repository path. This instance's upload
// chain runs through Cloudflare, whose origin timeout kills a multi-megabyte
// request outright, so a report that always uploaded would fail for exactly
// the large bundles an operator most needs to hand over. The push request
// carries only the scope — the server rebuilds the same document and commits
// it — and the comment keeps a link. When no repository is configured, or the
// push fails, the attachment path still runs and the report is not lost.
func reportLogBundle(ctx context.Context, cmd *cobra.Command, client *cli.APIClient, taskID string, bundle exportedBundle, filename string, body []byte) (map[string]any, error) {
	if bundle.Task.IssueID == "" {
		return nil, fmt.Errorf("--report needs an issue: this run is not linked to an issue")
	}

	mention, err := exportMention(ctx, cmd, client, bundle.Task.IssueID)
	if err != nil {
		return nil, err
	}

	push, pushErr := pushLogBundle(ctx, client, taskID, bundle)
	if pushErr != nil && !isLogRepoUnconfigured(pushErr) {
		fmt.Fprintln(os.Stderr, "Log repository push failed, reporting the attachment instead:", pushErr)
	}
	if pushErr == nil && push != nil && push.Pushed {
		content := logExportReportComment(push.SummaryMarkdown, mention, push.URL)
		var comment map[string]any
		if err := client.PostJSON(ctx, "/api/issues/"+bundle.Task.IssueID+"/comments", map[string]any{"content": content}, &comment); err != nil {
			return nil, fmt.Errorf("report log bundle: %w", err)
		}
		fmt.Fprintln(os.Stderr, "Pushed to the log repository and reported to issue", bundle.Task.IssueIdentifier)
		return map[string]any{
			"issue_id":   bundle.Task.IssueID,
			"comment_id": comment["id"],
			"mention":    mention,
			"channel":    "git",
			"url":        push.URL,
			"path":       push.Path,
			"branch":     push.Branch,
		}, nil
	}

	attachmentID, err := client.UploadFile(ctx, body, filename, bundle.Task.IssueID)
	if err != nil {
		return nil, fmt.Errorf("upload log bundle: %w", err)
	}

	content := strings.TrimSpace(bundle.SummaryMarkdown)
	if mention != "" {
		content = content + "\n\n" + mention
	}
	if content == "" {
		content = "运行日志导出"
	}

	payload := map[string]any{
		"content":        content,
		"attachment_ids": []string{attachmentID},
	}
	var comment map[string]any
	if err := client.PostJSON(ctx, "/api/issues/"+bundle.Task.IssueID+"/comments", payload, &comment); err != nil {
		return nil, fmt.Errorf("report log bundle: %w", err)
	}

	fmt.Fprintln(os.Stderr, "Reported to issue", bundle.Task.IssueIdentifier)
	result := map[string]any{
		"issue_id":      bundle.Task.IssueID,
		"comment_id":    comment["id"],
		"attachment_id": attachmentID,
		"mention":       mention,
		"channel":       "attachment",
	}
	if pushErr != nil {
		result["fallback_reason"] = pushErr.Error()
	}
	return result, nil
}

// pushLogBundle asks the server to commit the bundle into the workspace log
// repository. The request carries the scope rather than the artifact: the
// server rebuilds the document with the generator that produced the local
// copy, so the bytes cross no size-limited upload path.
//
// The rebuild means the committed file's `generated_at` is seconds newer than
// the local one, which is why the comment is composed from the summary the
// server returns instead of the one this command already holds.
func pushLogBundle(ctx context.Context, client *cli.APIClient, taskID string, bundle exportedBundle) (*logExportPush, error) {
	payload := map[string]any{"scope": bundle.Task.Scope.Kind}
	if bundle.Task.Scope.Kind == "hours" {
		payload["hours"] = bundle.Task.Scope.Hours
	}

	var push logExportPush
	if err := client.PostJSON(ctx, "/api/tasks/"+taskID+"/logs/export/push", payload, &push); err != nil {
		return nil, err
	}
	return &push, nil
}

// isLogRepoUnconfigured reports the ordinary "this workspace has no log
// repository" answer, which is a supported configuration rather than a
// failure worth a warning line.
func isLogRepoUnconfigured(err error) bool {
	var httpErr *cli.HTTPError
	if errors.As(err, &httpErr) {
		return httpErr.StatusCode == http.StatusConflict
	}
	return false
}

// logExportReportComment mirrors buildLogExportReportComment in
// packages/core/logs/report.ts: the bundle's own summary, then the link to the
// committed document, then the mention. Change one and change the other, or a
// CLI report and a UI report stop reading the same on the issue.
func logExportReportComment(summary, mention, link string) string {
	parts := []string{}
	if trimmed := strings.TrimSpace(summary); trimmed != "" {
		parts = append(parts, trimmed)
	}
	if href := strings.TrimSpace(link); href != "" {
		parts = append(parts, "日志包：["+href+"]("+href+")")
	}
	if len(parts) == 0 {
		parts = append(parts, "运行日志导出")
	}
	if target := strings.TrimSpace(mention); target != "" {
		parts = append(parts, target)
	}
	return strings.Join(parts, "\n\n")
}

// exportMention resolves the mention link for --report. An explicit --mention
// wins; otherwise the default only ever names a human member.
//
// A default mention must never name an agent or a squad: `mention://agent/<id>`
// enqueues a paid run, and the common report is an operator exporting the logs
// of a run that just died — which is usually the run of the very agent the
// issue is assigned to. Waking that agent back up is the opposite of what a
// post-mortem report should do. So when the assignee is not a member, the
// issue's human creator is notified instead; if nobody human is on the issue,
// nothing is mentioned rather than a guessed target.
func exportMention(ctx context.Context, cmd *cobra.Command, client *cli.APIClient, issueID string) (string, error) {
	if override, _ := cmd.Flags().GetString("mention"); override != "" {
		kind, id, ok := strings.Cut(override, ":")
		if !ok || kind == "" || id == "" {
			return "", fmt.Errorf("--mention must be <type>:<id> (type is member, agent, or squad)")
		}
		switch kind {
		case "member", "agent", "squad":
		default:
			return "", fmt.Errorf("--mention type %q is not member, agent, or squad", kind)
		}
		// An explicit agent/squad mention is the caller taking responsibility
		// for the run it may start, so it is passed through unchanged.
		return mentionLink(kind, id, "负责人"), nil
	}

	var issue struct {
		AssigneeType *string `json:"assignee_type"`
		AssigneeID   *string `json:"assignee_id"`
		CreatorType  *string `json:"creator_type"`
		CreatorID    *string `json:"creator_id"`
	}
	if err := client.GetJSON(ctx, "/api/issues/"+issueID, &issue); err != nil {
		return "", fmt.Errorf("load issue owner: %w", err)
	}

	// No assignee keeps the old "guess nobody" behavior; a human assignee is
	// the natural owner; an agent/squad assignee falls back to the human who
	// filed the issue.
	if issue.AssigneeType == nil || *issue.AssigneeType == "" {
		return "", nil
	}
	switch *issue.AssigneeType {
	case "member":
		if issue.AssigneeID != nil && *issue.AssigneeID != "" {
			return mentionLink("member", *issue.AssigneeID, "负责人"), nil
		}
	case "agent", "squad":
		if issue.CreatorType != nil && *issue.CreatorType == "member" && issue.CreatorID != nil && *issue.CreatorID != "" {
			return mentionLink("member", *issue.CreatorID, "创建人"), nil
		}
	}
	return "", nil
}

func mentionLink(kind, id, label string) string {
	return fmt.Sprintf("[@%s](mention://%s/%s)", label, kind, id)
}

// filenameFromHeaders reads the server-suggested artifact name. The server owns
// the naming so every client writes the same file.
func filenameFromHeaders(headers http.Header) string {
	disposition := headers.Get("Content-Disposition")
	if disposition == "" {
		return ""
	}
	const marker = `filename="`
	idx := strings.Index(disposition, marker)
	if idx < 0 {
		return ""
	}
	rest := disposition[idx+len(marker):]
	end := strings.IndexByte(rest, '"')
	if end < 0 {
		return ""
	}
	return filepath.Base(rest[:end])
}
