package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/multica-ai/multica/server/internal/cli"
)

var logsCmd = &cobra.Command{
	Use:   "logs",
	Short: "Export agent run logs",
}

var logsExportCmd = &cobra.Command{
	Use:   "export <task-id>",
	Short: "Export a redacted log bundle for a task run",
	Long: `Export a task run's structured transcript, run metadata, and an AI-ready
summary as one JSON bundle.

The bundle is generated by the server — the same generator behind the web and
desktop export dialogs — so the file this command writes is exactly the artifact
those surfaces preview and upload. Token-, password-, and environment-value
shaped material is masked before it ever leaves the server.

Ranges:
  run     this run only (default)
  hours   every run of the same issue whose entries fall in the last N hours
  task    the issue's whole run history

To report the bundle on the issue instead of keeping it local, pass --report:
the file is uploaded through the ordinary issue-comment attachment path and the
comment mentions the human who owns the issue. An agent- or squad-assigned
issue mentions its human creator instead, so reporting can never queue another
agent run; name one explicitly with --mention to override that.`,
	Example: `  # Export the run's log bundle into the current directory
  $ multica logs export 01a0b577-06b6-786e-8df6-3ebf70edf6d2

  # The last 6 hours of the issue's runs, written to ./exports
  $ multica logs export 01a0b577-06b6-786e-8df6-3ebf70edf6d2 --scope hours --hours 6 -o ./exports

  # Write the bundle to stdout (metadata goes to stderr), then report it
  $ multica logs export 01a0b577-06b6-786e-8df6-3ebf70edf6d2 --stdout > bundle.json

  # Export and report it on the issue in one action
  $ multica logs export 01a0b577-06b6-786e-8df6-3ebf70edf6d2 --report`,
	Args: exactArgs(1),
	RunE: runLogsExport,
}

func init() {
	logsCmd.AddCommand(logsExportCmd)
	logsExportCmd.Flags().String("scope", "run", "Export range: run, hours, or task")
	logsExportCmd.Flags().Int("hours", 0, "Lookback window in hours; required with --scope hours")
	logsExportCmd.Flags().StringP("output-dir", "o", ".", "Directory to write the bundle into")
	logsExportCmd.Flags().String("output-file", "", "Exact path to write the bundle to (overrides --output-dir)")
	logsExportCmd.Flags().Bool("stdout", false, "Write the bundle JSON to stdout instead of a file")
	logsExportCmd.Flags().Bool("report", false, "Also post the bundle as a comment attachment on the task's issue and mention its human owner")
	logsExportCmd.Flags().String("mention", "", "Override the --report mention as <type>:<id> (member, agent, or squad; an agent/squad mention queues a run)")
}

// exportedBundle is the subset of the artifact this command reads back. The
// artifact itself is opaque bytes here: re-encoding it would break the promise
// that the CLI writes exactly what the server produced.
type exportedBundle struct {
	Task struct {
		ID              string `json:"id"`
		IssueID         string `json:"issue_id"`
		IssueIdentifier string `json:"issue_identifier"`
		Scope           struct {
			Kind  string `json:"kind"`
			Hours int    `json:"hours"`
		} `json:"scope"`
	} `json:"task"`
	RunCount   int  `json:"run_count"`
	EntryCount int  `json:"entry_count"`
	Truncated  bool `json:"truncated"`
	// Redaction is the artifact's own statement about its masking. A bundle
	// built from a run whose environment could not be read is only
	// pattern-redacted, and the CLI surfaces that rather than letting the
	// summary's "已自动脱敏" line stand unqualified. It is a pointer so an
	// artifact from a server that predates the marker reads as "unknown"
	// instead of falsely reading as "incomplete".
	Redaction *struct {
		Complete bool   `json:"complete"`
		Note     string `json:"note,omitempty"`
	} `json:"redaction"`
	SummaryMarkdown string `json:"summary_markdown"`
}

func runLogsExport(cmd *cobra.Command, args []string) error {
	scope, _ := cmd.Flags().GetString("scope")
	hours, _ := cmd.Flags().GetInt("hours")
	if err := validateLogsExportScope(scope, hours); err != nil {
		return err
	}

	client, err := newAPIClient(cmd)
	if err != nil {
		return err
	}

	// A report uploads the bundle, so give the request the same longer budget
	// the comment-attachment path uses.
	timeout := cli.APITimeout()
	if report, _ := cmd.Flags().GetBool("report"); report {
		timeout = cli.AtLeastAPITimeout(60 * time.Second)
	}
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	path := "/api/tasks/" + args[0] + "/logs/export?scope=" + scope
	if scope == "hours" {
		path += "&hours=" + strconv.Itoa(hours)
	}
	body, headers, err := client.GetBytes(ctx, path)
	if err != nil {
		return fmt.Errorf("export logs: %w", err)
	}

	var bundle exportedBundle
	if err := json.Unmarshal(body, &bundle); err != nil {
		return fmt.Errorf("decode log bundle: %w", err)
	}

	filename := filenameFromHeaders(headers)
	if filename == "" {
		filename = "log-export.json"
	}

	result := map[string]any{
		"task_id":          bundle.Task.ID,
		"issue_id":         bundle.Task.IssueID,
		"issue_identifier": bundle.Task.IssueIdentifier,
		"scope":            bundle.Task.Scope.Kind,
		"run_count":        bundle.RunCount,
		"entry_count":      bundle.EntryCount,
		"truncated":        bundle.Truncated,
		"summary_markdown": bundle.SummaryMarkdown,
	}
	if bundle.Redaction != nil && !bundle.Redaction.Complete {
		result["redaction_complete"] = false
		result["redaction_note"] = bundle.Redaction.Note
	}

	// stdout is the artifact's channel. `multica logs export <id> --stdout >
	// bundle.json` must produce a file that parses as exactly one JSON
	// document, so in that mode the metadata JSON moves to stderr rather than
	// being appended to the bundle on stdout.
	metaOut := io.Writer(os.Stdout)
	toStdout, _ := cmd.Flags().GetBool("stdout")
	if toStdout {
		if _, err := os.Stdout.Write(body); err != nil {
			return fmt.Errorf("write bundle to stdout: %w", err)
		}
		metaOut = os.Stderr
	} else {
		dest, err := writeLogBundle(cmd, filename, body)
		if err != nil {
			return err
		}
		result["path"] = dest
		result["filename"] = filename
		result["size_bytes"] = len(body)
		fmt.Fprintln(os.Stderr, "Exported:", dest)
	}

	if report, _ := cmd.Flags().GetBool("report"); report {
		reported, err := reportLogBundle(ctx, cmd, client, bundle, filename, body)
		if err != nil {
			return err
		}
		result["report"] = reported
	}

	return cli.PrintJSON(metaOut, result)
}

func validateLogsExportScope(scope string, hours int) error {
	switch scope {
	case "run", "task":
		if hours != 0 {
			return fmt.Errorf("--hours only applies to --scope hours")
		}
	case "hours":
		if hours <= 0 {
			return fmt.Errorf("--scope hours requires --hours N (1-%d)", 24*30)
		}
	default:
		return fmt.Errorf("invalid --scope %q: want run, hours, or task", scope)
	}
	return nil
}

// writeLogBundle writes the artifact and returns its absolute path. The output
// directory is created so `-o ./exports` works in a clean workdir.
func writeLogBundle(cmd *cobra.Command, filename string, body []byte) (string, error) {
	if explicit, _ := cmd.Flags().GetString("output-file"); explicit != "" {
		if dir := filepath.Dir(explicit); dir != "" && dir != "." {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return "", fmt.Errorf("create output directory: %w", err)
			}
		}
		if err := os.WriteFile(explicit, body, 0o644); err != nil {
			return "", fmt.Errorf("write bundle: %w", err)
		}
		abs, err := filepath.Abs(explicit)
		if err != nil {
			return explicit, nil
		}
		return abs, nil
	}

	outputDir, _ := cmd.Flags().GetString("output-dir")
	if outputDir == "" {
		outputDir = "."
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return "", fmt.Errorf("create output directory: %w", err)
	}
	dest := filepath.Join(outputDir, filename)
	if err := os.WriteFile(dest, body, 0o644); err != nil {
		return "", fmt.Errorf("write bundle: %w", err)
	}
	abs, err := filepath.Abs(dest)
	if err != nil {
		return dest, nil
	}
	return abs, nil
}

// reportLogBundle uploads the artifact through the existing issue-comment
// attachment chain and posts a comment that mentions the issue's owner. It is
// the same two calls the web dialog makes, so a CLI report and a UI report are
// indistinguishable on the issue.
func reportLogBundle(ctx context.Context, cmd *cobra.Command, client *cli.APIClient, bundle exportedBundle, filename string, body []byte) (map[string]any, error) {
	if bundle.Task.IssueID == "" {
		return nil, fmt.Errorf("--report needs an issue: this run is not linked to an issue")
	}

	attachmentID, err := client.UploadFile(ctx, body, filename, bundle.Task.IssueID)
	if err != nil {
		return nil, fmt.Errorf("upload log bundle: %w", err)
	}

	content := strings.TrimSpace(bundle.SummaryMarkdown)
	mention, err := exportMention(ctx, cmd, client, bundle.Task.IssueID)
	if err != nil {
		return nil, err
	}
	if mention != "" {
		content = content + "\n\n" + mention
	}
	if content == "" {
		content = "运行日志导出"
	}

	payload := map[string]any{
		"content":        content,
		"attachment_ids": []string{attachmentID},
	}
	var comment map[string]any
	if err := client.PostJSON(ctx, "/api/issues/"+bundle.Task.IssueID+"/comments", payload, &comment); err != nil {
		return nil, fmt.Errorf("report log bundle: %w", err)
	}

	fmt.Fprintln(os.Stderr, "Reported to issue", bundle.Task.IssueIdentifier)
	return map[string]any{
		"issue_id":      bundle.Task.IssueID,
		"comment_id":    comment["id"],
		"attachment_id": attachmentID,
		"mention":       mention,
	}, nil
}

// exportMention resolves the mention link for --report. An explicit --mention
// wins; otherwise the default only ever names a human member.
//
// A default mention must never name an agent or a squad: `mention://agent/<id>`
// enqueues a paid run, and the common report is an operator exporting the logs
// of a run that just died — which is usually the run of the very agent the
// issue is assigned to. Waking that agent back up is the opposite of what a
// post-mortem report should do. So when the assignee is not a member, the
// issue's human creator is notified instead; if nobody human is on the issue,
// nothing is mentioned rather than a guessed target.
func exportMention(ctx context.Context, cmd *cobra.Command, client *cli.APIClient, issueID string) (string, error) {
	if override, _ := cmd.Flags().GetString("mention"); override != "" {
		kind, id, ok := strings.Cut(override, ":")
		if !ok || kind == "" || id == "" {
			return "", fmt.Errorf("--mention must be <type>:<id> (type is member, agent, or squad)")
		}
		switch kind {
		case "member", "agent", "squad":
		default:
			return "", fmt.Errorf("--mention type %q is not member, agent, or squad", kind)
		}
		// An explicit agent/squad mention is the caller taking responsibility
		// for the run it may start, so it is passed through unchanged.
		return mentionLink(kind, id, "负责人"), nil
	}

	var issue struct {
		AssigneeType *string `json:"assignee_type"`
		AssigneeID   *string `json:"assignee_id"`
		CreatorType  *string `json:"creator_type"`
		CreatorID    *string `json:"creator_id"`
	}
	if err := client.GetJSON(ctx, "/api/issues/"+issueID, &issue); err != nil {
		return "", fmt.Errorf("load issue owner: %w", err)
	}

	// No assignee keeps the old "guess nobody" behavior; a human assignee is
	// the natural owner; an agent/squad assignee falls back to the human who
	// filed the issue.
	if issue.AssigneeType == nil || *issue.AssigneeType == "" {
		return "", nil
	}
	switch *issue.AssigneeType {
	case "member":
		if issue.AssigneeID != nil && *issue.AssigneeID != "" {
			return mentionLink("member", *issue.AssigneeID, "负责人"), nil
		}
	case "agent", "squad":
		if issue.CreatorType != nil && *issue.CreatorType == "member" && issue.CreatorID != nil && *issue.CreatorID != "" {
			return mentionLink("member", *issue.CreatorID, "创建人"), nil
		}
	}
	return "", nil
}

func mentionLink(kind, id, label string) string {
	return fmt.Sprintf("[@%s](mention://%s/%s)", label, kind, id)
}

// filenameFromHeaders reads the server-suggested artifact name. The server owns
// the naming so every client writes the same file.
func filenameFromHeaders(headers http.Header) string {
	disposition := headers.Get("Content-Disposition")
	if disposition == "" {
		return ""
	}
	const marker = `filename="`
	idx := strings.Index(disposition, marker)
	if idx < 0 {
		return ""
	}
	rest := disposition[idx+len(marker):]
	end := strings.IndexByte(rest, '"')
	if end < 0 {
		return ""
	}
	return filepath.Base(rest[:end])
}
