-- Routing decision comments (DENE-633).
--
-- The routing layer posts at most one comment of each kind per issue: the
-- todo-row decision, the in-review handoff, the blocked-row advice, and the
-- one-off "model unavailable" notice. That cap is what keeps a ticket whose
-- status is flipped back and forth from collecting duplicate comments and
-- re-notifying the same person.
--
-- A nullable marker column, not a new `type` value, for the two reasons
-- migration 239 already recorded for quick actions: re-adding comment_type_check
-- takes ACCESS EXCLUSIVE on one of the hottest tables in the product, and
-- `type` is client-supplied on the generic POST /comments path, so a member
-- could post a comment that renders as a routing decision. There is no request
-- field for routing_kind — only the routing module sets it — so this marker
-- cannot be forged.
--
-- No FK per repo policy.
ALTER TABLE comment ADD COLUMN IF NOT EXISTS routing_kind TEXT;
